oauth2:
  host: http://localhost:${server.port}/iam

service:
  security:
    excludeUris:
      - /oauth/**
      - /login/**
      - /logout
    mock:
      enable: true
      user-id: 1
      username: name
      access: 6
      roles: RD:ADMIN